"""rename plan_in_hours to plan_in_days

Revision ID: 089357298a21
Revises: c7b599a54001
Create Date: 2024-09-01 17:30:12.411776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089357298a21'
down_revision: Union[str, None] = 'c7b599a54001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('plan_in_days', sa.Integer(), nullable=False))
    op.drop_column('task', 'plan_in_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('plan_in_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'plan_in_days')
    # ### end Alembic commands ###
