"""Added column user_count_by_plan to task

Revision ID: 2509e85a3f41
Revises: 707f8db71925
Create Date: 2024-09-04 14:11:13.945675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2509e85a3f41'
down_revision: Union[str, None] = '707f8db71925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_count_by_plan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_count_by_plan')
    # ### end Alembic commands ###
