"""empty message

Revision ID: 896756a4419d
Revises: f32991afed33
Create Date: 2024-09-30 21:49:08.133870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896756a4419d'
down_revision: Union[str, None] = 'f32991afed33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('changes', sa.Column('task_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('kpi', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kpi')
    op.drop_column('changes', 'task_id')
    # ### end Alembic commands ###
