"""Rename employee to user

Revision ID: a90c5a7bf24c
Revises: 5223eacf8e38
Create Date: 2024-05-16 04:41:05.700091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90c5a7bf24c'
down_revision: Union[str, None] = '5223eacf8e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('employee', 'user')

    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'employee')
    # ### end Alembic commands ###
