"""Add column plan in hours to task

Revision ID: c7b599a54001
Revises: cfd31858dd15
Create Date: 2024-07-27 20:40:12.879523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b599a54001'
down_revision: Union[str, None] = 'cfd31858dd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('plan_in_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'plan_in_hours')
    # ### end Alembic commands ###
