"""Add user count to task table

Revision ID: cfd31858dd15
Revises: 47f306b29d81
Create Date: 2024-07-26 19:37:29.414931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd31858dd15'
down_revision: Union[str, None] = '47f306b29d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_count')
    # ### end Alembic commands ###
