"""Delete assignment task because dont need anymore

Revision ID: e7c6d7fdfe90
Revises: dce66889c188
Create Date: 2024-07-08 22:35:16.989928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c6d7fdfe90'
down_revision: Union[str, None] = 'dce66889c188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], name='assignment_task_object_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='assignment_task_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignment_task_pkey')
    )
    # ### end Alembic commands ###
